# Generated by Django 4.1.1 on 2022-09-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Actividad Económica')),
            ],
            options={
                'verbose_name': 'Actividad Económica',
                'verbose_name_plural': 'Actividades Económicas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CompensacionFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Afiliado al Sistema de Compensación Familiar?')),
            ],
            options={
                'verbose_name': 'Afiliado a la Caja de Compensación',
                'verbose_name_plural': 'Afiliados a la Caja de Compensaciónes',
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Existen personas con Discapacidad en el grupo Familiar?')),
            ],
            options={
                'verbose_name': 'Persona con Discapacidad',
                'verbose_name_plural': 'Personas con Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Estado Civil')),
            ],
            options={
                'verbose_name': 'Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='Geografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Geografica')),
            ],
            options={
                'verbose_name': 'Geografica',
                'verbose_name_plural': 'Geograficas',
            },
        ),
        migrations.CreateModel(
            name='IngresosTotalesFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0, editable=False, unique=True, verbose_name='Ingresos totales Familiares')),
            ],
            options={
                'verbose_name': 'Ingreso Total Familiar',
                'verbose_name_plural': 'Ingresos totales Familiares',
            },
        ),
        migrations.CreateModel(
            name='LugarProcedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Lugar de procedencia del Grupo Familiar')),
            ],
            options={
                'verbose_name': 'Procedencia',
                'verbose_name_plural': 'Procedencias',
            },
        ),
        migrations.CreateModel(
            name='NivelEscolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Nivel Escolaridad')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='NumeroHogares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=3, unique=True, verbose_name='Numero de Hogares en la Vivienda')),
            ],
            options={
                'verbose_name': 'numero de hogares',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Ocupación')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Parentesco')),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
            },
        ),
        migrations.CreateModel(
            name='Pensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Algún integrante hace aportes al sistema de pensiones?')),
            ],
            options={
                'verbose_name': 'Algún integrante hace aportes al sistema de pensiones',
                'verbose_name_plural': 'Algunos integrantes hacen aportes al sistema de pensiones',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='SistemaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Tipo de sistema de Salud?')),
            ],
            options={
                'verbose_name': 'Tipo de Sistema de Salud',
                'verbose_name_plural': 'Tipos de Sistemas de Salud',
            },
        ),
        migrations.CreateModel(
            name='SituacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Situación laboral del Jefe de Hogar')),
            ],
            options={
                'verbose_name': 'Situación laboral',
                'verbose_name_plural': 'Situaciones Laborales',
            },
        ),
        migrations.CreateModel(
            name='TiempoViviendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=3, unique=True, verbose_name='Tiempo viviendo en el Municipio')),
            ],
            options={
                'verbose_name': 'Tiempo viviendo',
            },
        ),
        migrations.CreateModel(
            name='TipologiaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Tipología Familiar')),
            ],
            options={
                'verbose_name': 'Tipologia Familiar',
                'verbose_name_plural': 'Tipologia Familiares',
            },
        ),
        migrations.CreateModel(
            name='TrabajoEsporadico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='Trabaja Esporádicamente?')),
            ],
            options={
                'verbose_name': 'Trabajo Esporádico',
                'verbose_name_plural': 'Trabajos Esporádicos',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('resolucion_numero', models.IntegerField(blank=True, default=0, editable=False, unique=True, verbose_name='Numero de Resolución')),
                ('resolucion_pdf', models.FileField(null=True, upload_to='', verbose_name='Agregar Archivo de Resolución')),
                ('fecha', models.DateField(auto_now_add=True, unique=True, verbose_name='Fecha de Realización')),
                ('ficha', models.IntegerField(default=0, editable=False, unique=True, verbose_name='Numero de ficha')),
                ('responsable', models.CharField(max_length=100, verbose_name='Profesional Responsable')),
                ('nombre_suministro_de_informacion', models.CharField(max_length=100, verbose_name='Nombre de quien suministra la Información')),
                ('apellido_suministro_de_informacion', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula_suministro_de_informacion', models.IntegerField(default=0, editable=False, unique=True, verbose_name='C.C')),
                ('parentesco_suministro_de_informacion', models.CharField(max_length=100, verbose_name='Parentesco con el Jefe de Hogar')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('direccion_municipio', models.CharField(max_length=100, verbose_name='Direccion de Municipio')),
                ('telefono_municipio', models.IntegerField(blank=True, default=0, editable=False, unique=True, verbose_name='Numero de Resolución')),
                ('corregimiento', models.CharField(blank=True, max_length=100, verbose_name='Corregimiento')),
                ('nombre_jefe_hogar', models.CharField(max_length=100, verbose_name='Nombre del Jefe de Hogar')),
                ('cedula_jefe_hogar', models.IntegerField(default=0, editable=False, unique=True, verbose_name='Cédula Jefe de Hogar')),
                ('lugar_expedicion_cedula_jefe', models.CharField(max_length=100, verbose_name='Lugar de Expedición de la Cédula')),
                ('nombre_conyugue', models.CharField(blank=True, max_length=100, verbose_name='Nombre del conyugue')),
                ('cedula_conyugue', models.IntegerField(default=0, editable=False, unique=True, verbose_name='Cédula Conyugue')),
                ('lugar_expedicion_conyugue', models.CharField(max_length=100, verbose_name='Lugar de Expedición de la Cédula')),
                ('composicion_familiar_nom_ape', models.CharField(blank=True, max_length=100, verbose_name='Nombres')),
                ('edad', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Edad')),
                ('tipologia_familiar_otra', models.TextField(blank=True, max_length=600, verbose_name='Otra Tipología')),
                ('arraigo_lugar_de_procedencia_tiempo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Cúantos?')),
                ('tiempo_residencia_municipio', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Hace cuántos? años reside en el Municipio')),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la Empresa')),
                ('telefono_empresa', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Teléfono de la Empresa')),
                ('trabajo_esporadico_actividad', models.CharField(blank=True, max_length=100, verbose_name='En qué Actividad?')),
                ('jubilado', models.BooleanField(default=False, verbose_name='Jubilado?')),
                ('desempleado', models.BooleanField(default=False, verbose_name='Desempleado?')),
                ('desempleado_tiempo', models.CharField(blank=True, max_length=100, verbose_name='Hace Cuánto?')),
                ('trabaja_conyugue', models.BooleanField(default=False, verbose_name='Trabaja el Conyugue?')),
                ('conyugue_tiempo_trabajo', models.CharField(blank=True, max_length=100, verbose_name='Quién o Quiénes?')),
                ('nombre_empresa_conyugue', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la Empresa')),
                ('telefono_empresa_conyugue', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Teléfono de la Empresa')),
                ('personas_a_cargo_jefe_hogar', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='No de personas a cargo del Jefe de Hogar')),
                ('cual_caja_compensaciones', models.CharField(blank=True, max_length=100, verbose_name='Cuál Caja?')),
                ('cuantas_discapacidad_familia', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Cuántas personas?')),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=100, verbose_name='Qué tipo de discapacidad?')),
                ('imagen_firma', models.ImageField(null=True, upload_to='', verbose_name='Agregar Imagen de la Firma')),
                ('planos', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Agregar Planos')),
                ('actividad_economica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividadeconomica', verbose_name='Actividad Económica')),
                ('arraigo_lugar_procedencia_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lugarprocedencia', verbose_name='Lugar de Procedencia del grupo Familiar')),
                ('arraigo_tiempo_viviendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiempoviviendo', verbose_name='Tiempo que lleva viviendo en el Municipio')),
                ('aspecto_economico_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.situacionlaboral', verbose_name='Situación laboral del Jefe de Hogar')),
                ('caja_de_compensación_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compensacionfamiliar', verbose_name='Alguno de los Miembros hace Aportes al sistema de Salud?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Seleccione la Categoria del producto')),
                ('discapacidad_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discapacidad', verbose_name='Existen Personas dentro de la Familia con Discapacidad?')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadocivil', verbose_name='Estado Civil')),
                ('ingresos_familaires_totales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingresostotalesfamiliares', verbose_name='Ingresos Totales Familiares')),
                ('nivel_escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivelescolaridad', verbose_name='Nivel de Escolaridad')),
                ('numero_hogares_en_vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.numerohogares', verbose_name='Numero de Hogares en la Vivienda')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ocupacion', verbose_name='Ocupación')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parentesco', verbose_name='Parentesco con el Jefe de Hogar')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sexo', verbose_name='Sexo')),
                ('sistema_de_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sistemasalud', verbose_name='Qué tipo de sistema de Salud tiene la Familia?')),
                ('sistema_pensiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pensiones', verbose_name='Algún integrante hace aportes al sistema de pensiones?')),
                ('tipologia_familar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipologiafamiliar', verbose_name='Tipologia Familiar')),
                ('trabajo_esporadico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trabajoesporadico', verbose_name='Trabajo Esporadico?')),
                ('ubicacion_geografica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.geografica', verbose_name='Seleccione su tipo de residencia')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
    ]
