# Generated by Django 4.1.1 on 2022-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='imagen_firma',
            field=models.ImageField(null=True, upload_to='firmas', verbose_name='Agregar Imagen de la Firma'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='planos',
            field=models.ImageField(blank=True, null=True, upload_to='planos', verbose_name='Agregar Planos'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='resolucion_pdf',
            field=models.FileField(null=True, upload_to='resoluciones', verbose_name='Agregar Archivo de Resolución'),
        ),
    ]
