# Generated by Django 4.1.1 on 2022-09-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_formulario_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='numero_hogares_en_vivienda',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Número de hoogares en la Vivienda'),
        ),
        migrations.DeleteModel(
            name='NumeroHogares',
        ),
    ]
