# Generated by Django 4.1.1 on 2022-09-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_formulario_arraigo_lugar_de_procedencia_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='arraigo_lugar_de_procedencia_tiempo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='De Donde?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tiempo_residencia_municipio',
            field=models.IntegerField(default=0, null=True, verbose_name='Hace cuántos? años reside en el Municipio'),
        ),
        migrations.AlterField(
            model_name='tiempoviviendo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tiempo viviendo en el Municipio'),
        ),
    ]
