# Generated by Django 4.1.1 on 2022-09-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_formulario_arraigo_lugar_de_procedencia_tiempo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacionlaboral',
            options={'verbose_name': 'Actividad Económica', 'verbose_name_plural': 'Actividades Económicas'},
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='desempleado',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='jubilado',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cuál es su Actividad Económica'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='arraigo_lugar_de_procedencia_tiempo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sí contesto mas de 16 años, Cuántos Años lleva en el municipio?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='desempleado_tiempo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hace Cuánto esta Desempleado?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teléfono de la Empresa'),
        ),
        migrations.AlterField(
            model_name='ingresostotalesfamiliares',
            name='name',
            field=models.CharField(max_length=90, unique=True, verbose_name='Ingresos totales'),
        ),
        migrations.DeleteModel(
            name='ActividadEconomica',
        ),
    ]
