# Generated by Django 4.1.1 on 2022-09-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_situacionlaboral_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cedula_suministro_de_informacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cédula de suministrante de la información'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono_municipio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teléfono Del suministrante de la información'),
        ),
    ]
