# Generated by Django 4.1.1 on 2022-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_formulario_cedula_suministro_de_informacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cedula_conyugue',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cédula del conyugue'),
        ),
    ]
