# Generated by Django 4.1.1 on 2022-09-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_formulario_lugar_expedicion_informacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cedula_jefe_hogar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cédula de Jefe de Hogar'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='ficha',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ficha N°'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='imagen_firma',
            field=models.ImageField(null=True, upload_to='./firmas', verbose_name='Agregar Imagen de la Firma'),
        ),
    ]
