# Generated by Django 4.1.1 on 2022-09-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_formulario_imagen_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='imagen_firma',
            field=models.ImageField(null=True, upload_to='firmas', verbose_name='Agregar Imagen de la Firma'),
        ),
    ]
