# Generated by Django 4.1.1 on 2022-09-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_formulario_imagen_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='planos',
            field=models.ImageField(blank=True, null=True, upload_to='./planos', verbose_name='Agregar Planos'),
        ),
    ]
