# Generated by Django 4.1.1 on 2022-09-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_formulario_imagen_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='edad',
            field=models.CharField(max_length=100, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='imagen_firma',
            field=models.ImageField(null=True, upload_to='firma', verbose_name='Agregar Imagen de la Firma'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='planos',
            field=models.ImageField(blank=True, null=True, upload_to='planos', verbose_name='Agregar Planos'),
        ),
    ]
