# Generated by Django 4.1.1 on 2022-09-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_formulario_edad_alter_formulario_imagen_firma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='trabaja_conyugue',
        ),
        migrations.AddField(
            model_name='formulario',
            name='conyugue_trabaja',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conyugue Trabaja?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='numero_hogares_en_vivienda',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de viviendas en el Hogar'),
        ),
    ]
