# Generated by Django 4.1.1 on 2022-09-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_formulario_trabaja_conyugue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='conyugue_trabaja',
            field=models.CharField(blank=True, max_length=100, verbose_name='Su Conyugue Trabaja?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono_empresa_conyugue',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teléfono de la Empresa donde trabaja su conyugue'),
        ),
    ]
