# Generated by Django 4.1.1 on 2022-09-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_formulario_conyugue_trabaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='personas_a_cargo_jefe_hogar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Perosnas a cargo del jefe de familia'),
        ),
    ]
