# Generated by Django 4.1.1 on 2022-09-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_formulario_personas_a_cargo_jefe_hogar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cuantas_discapacidad_familia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cuántas Personas?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qué tipo de discapacidad?'),
        ),
    ]
