# Generated by Django 4.1.1 on 2022-09-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_formulario_cuantas_discapacidad_familia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cuantas_discapacidad_familia',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cuántas Personas?'),
        ),
    ]
