# Generated by Django 4.1.1 on 2022-09-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_formulario_cuantas_discapacidad_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='trabaja_conyugue',
            field=models.CharField(blank=True, max_length=100, verbose_name='Su Conyugue Trabaja?2'),
        ),
    ]
