# Generated by Django 4.1.1 on 2022-10-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_formulario_trabaja_conyugue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='discapacidad_familiar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.discapacidad', verbose_name='Existen Personas dentro de la Familia con Discapacidad?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='lugar_expedicion_informacion',
            field=models.CharField(max_length=100, verbose_name='Lugar de Expedición de la Cédula del que suministra la Información'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabajo_esporadico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.trabajoesporadico', verbose_name='Trabajo Esporadico?'),
        ),
    ]
